language: python

sudo: required
cache: pip
dist: "bionic"

services:
  - mysql
  - redis-server

python:
  - '2.7'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install -e .

before_script:
  - pip install coverage
  - pip install codecov
  - pip install redis

before_install:
  - mysql -e 'create database pydal;'

script: export COVERAGE_PROCESS_START=gluon/tests/coverage.ini; ./web2py.py --run_system_tests --with_coverage

after_success:
  - coverage combine;
  - codecov

notifications:
  email: true
